"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-$a=0=omhq&u5)_!a62w!susqi&&vnb0op@lyh$f_rjp*wvsnp&"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition
from .local import INSTALLED_APPS
from .local import MIDDLEWARE
from .local import DATABASES

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
]

CORS_ALLOW_CREDENTIALS = True

STATIC_THEME_PATH = 'theme/img'

ROOT_URLCONF = "main.urls"

theme_name = "core/theme/templates"
admin_panel = "core/admin/templates"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, admin_panel),
            os.path.join(BASE_DIR, theme_name),
            ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "home.context_processors.load_settings",
                "home.context_processors.load_categories",
                "home.context_processors.socials",
                "home.context_processors.emails",
                "home.context_processors.phones",
                "home.context_processors.phones_header",
            ],
        },
    },
]


WSGI_APPLICATION = "main.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
SITE_ID = 1

from .local import LOGGING

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "ru-ru"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "core/"
STATIC_ROOT = "/main/core"

STATICFILES_DIRS = [
    BASE_DIR / "core",
    "/core/",
]


MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

CKEDITOR_5_CONFIGS = {
    'default': {
        'language': 'ru',
        'width': '100%',
        'toolbar': [
            'heading', '|',
            'bold', 'italic', 'underline', 'strikethrough', '|',
            'link', 'blockQuote', 'imageUpload', 'mediaEmbed', '|',
            'bulletedList', 'numberedList', '|',
            'undo', 'redo', '|',
            'sourceEditing'
        ],
        'htmlSupport': {
            'allow': [
                {
                    'name': 'video',
                    'attributes': True,
                    'classes': True,
                    'styles': True,
                },
                {
                    'name': 'source',
                    'attributes': True,
                    'classes': True,
                    'styles': True,
                },
                {
                    'name': 'div',
                    'attributes': True,
                    'classes': True,
                    'styles': True,
                }
            ]
        },
        'mediaEmbed': {
            'previewsInData': True,
        }
    },
    'extends': {
        'language': 'ru',
        'toolbar': [
            'heading', '|',
            'bold', 'italic', 'underline', 'strikethrough', '|',
            'link', 'blockQuote', 'imageUpload', 'mediaEmbed', '|',
            'bulletedList', 'numberedList', '|',
            'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', '|',
            'alignment', 'indent', 'outdent', '|',
            'code', 'codeBlock', '|',
            'undo', 'redo', '|',
            'sourceEditing'
        ],
        'image': {
            'toolbar': [
                'imageTextAlternative', '|',
                'imageStyle:alignLeft',
                'imageStyle:full',
                'imageStyle:alignRight'
            ],
            'styles': ['full', 'alignLeft', 'alignRight']
        },
        'htmlSupport': {
            'allow': [
                {
                    'name': 'video',
                    'attributes': True,
                    'classes': True,
                    'styles': True,
                },
                {
                    'name': 'source',
                    'attributes': True,
                    'classes': True,
                    'styles': True,
                },
                {
                    'name': 'div',
                    'attributes': True,
                    'classes': True,
                    'styles': True,
                }
            ]
        },
        'mediaEmbed': {
            'previewsInData': True,
        }
    }
}


INTERNAL_IPS = [
    "127.0.0.1",
    "localhost:3000",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = "users.User"

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.beget.com'
EMAIL_HOST_USER = 'info@xn----7sbah6bllcobpj.xn--p1ai'
EMAIL_HOST_PASSWORD = 'Ie51587v' 
EMAIL_FROM = 'info@xn----7sbah6bllcobpj.xn--p1ai' 
EMAIL_PORT = 465 
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False

RECAPTCHA_PUBLIC_KEY = '6LfYJQUqAAAAANqyj-hN9bAMzxy5TNZy8CMYd73W'
RECAPTCHA_PRIVATE_KEY = '6LfYJQUqAAAAAKCcl1__tYxIgAK7KbPkNMarYp5V'
RECAPTCHA_REQUIRED_SCORE = 0.5

CKEDITOR_UPLOAD_PATH = "uploads/"

# RECAPTCHA_DEFAULT_ACTION = 'generic'
# RECAPTCHA_SCORE_THRESHOLD = 0.5

# Переопределяем путь для @login_required - если пользовательно не авторизован, то перенаправить на страницу login  а не 404
# LOGIN_URL = 'user/login/'
